name: build-deploy

on: 
  push:
    tags:
      - 'v*.*.*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
      - name: Install dependencies
        run: go mod tidy
      - name: Test with the Go CLI
        run: go test
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: olegtarasov/get-tag@v2.1.3
        id: tagName
      - name: Build and push the image
        run: |
          docker login --username Jason-CKY --password ${{ secrets.GH_PAT }} ghcr.io
          docker build -f ./build/Dockerfile --tag ghcr.io/jason-cky/url-resolver:$GIT_TAG_NAME --target production .
          docker push ghcr.io/jason-cky/url-resolver:$GIT_TAG_NAME
          docker tag ghcr.io/jason-cky/url-resolver:$GIT_TAG_NAME ghcr.io/jason-cky/url-resolver:latest
          docker push ghcr.io/jason-cky/url-resolver:latest
